version: '2.3'
services:
    zookeeper:
        container_name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181
            - ZOOKEEPER_TICK_TIME:2000
        healthcheck:
          test: ["CMD", "nc", "-z", "zookeeper", "2181"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 30s

    kafka:
        container_name: kafka
        image: confluentinc/cp-kafka:latest
        depends_on:
            zookeeper:
                condition: service_healthy
        ports:
            - 29092:29092
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        healthcheck:
            test: ["CMD", "nc", "-vz", "localhost", "29092"]
            interval: 10s
            timeout: 10s
            retries: 15

    producer-image:
        container_name: producer
        build: ./
        env_file:
            - .env
        depends_on:
            kafka:
                condition: service_healthy
        ports:
            - 8080:8080

    consumer-image:
        container_name: consumer
        build: ../ms-consumer/
        env_file:
            - .env
        depends_on:
            kafka:
                condition: service_healthy

networks:
    default:
        name: microservices_network
